export type Capability =
  | "VIEW_DASHBOARD"
  | "VIEW_MANUFACTURING"
  | "VIEW_VISION"
  | "VIEW_LOGIC"
  | "VIEW_INFRA"
  | "VIEW_ANALYTICS"
  | "VIEW_SIMULATION"
  | "VIEW_GOVERNANCE"
  | "VIEW_ADMIN"
  | "VIEW_REGISTRY"
  | "VIEW_INTEGRATIONS"
  | "VIEW_SETTINGS";
